using HashTable;
myMapNode<string, string> myMap = new myMapNode<string, string>(10);
myMap.Add("0", "Paranoids");
myMap.Add("1", "are");
myMap.Add("2", "not");
myMap.Add("3", "paranoid");
myMap.Add("4", "because");
myMap.Add("6", "they");
myMap.Add("7", "are");
myMap.Add("8", "paranoid");
myMap.Add("9", "but");
myMap.Add("10", "because");
myMap.Add("11", "they");
myMap.Add("12", "keep");
myMap.Add("13", "themselves");
myMap.Add("14", "deliberately");
myMap.Add("15", "into");
myMap.Add("16", "paranoid");
myMap.Add("17", "avoidable");
myMap.Add("18", "situations");
string hash = myMap.Get("1");
Console.WriteLine("index value: " + hash);